blog_project/blog/urls.py
from django.urls import path
from .views import ( PostCreateView, 
                    PostUpdateView, 
                    PostDeleteView, 
                    PostDetailView, 
                    PostListView, 
                    UserPostListView, about ) 

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('about/', about, name='about'),
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'users'
urlpatterns = [
    path('registar/', views.register,name='register'),
    path('perfil/', views.perfil,name='perfil'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

blog_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.title} - {self.author.username}'
    
    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

blog_project/users/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Perfil(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    imagem = models.ImageField(default='default.jpg',upload_to='ImgPerfil')

    def __str__(self):
        return f'Perfil - {self.user.username}'
    
    def save(self, *args, **kwargs):
        super().save(*args,**kwargs)
        
        img = Image.open(self.imagem.path)
        
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.imagem.path)

blog_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Perfil

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email'] 
        
class PerfilUpdateForm(forms.ModelForm):    
    class Meta:
        model = Perfil
        fields = ['imagem'] 

blog_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.contrib.auth.models import User
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5
    
class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5
    
    # Sobrescrever a queryset padrão da ListView
    def get_queryset(self):
        user = get_object_or_404(User,username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')
    
class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    # Verificar se o usuário que está tentar editar o post é o mesmo que criou
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    # Rota de redirecionamento quando o post for eliminado com sucesso
    success_url = '/'
    
    # Verificar se o usuário que está tentar editar o post é o mesmo que criou
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
def about(request):
    return render(request,'blog/about.html',{'title':'About'})

blog_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import PerfilUpdateForm, UserRegisterForm, UserUpdateForm
from django.contrib import messages

# Registar Usuário.
def register(request):
    """
    Registar Usuário.
    """
    if request.method=='POST':
        # Formulario de registar usuario
        form = UserRegisterForm(request.POST)
        # Validar o formulario de registar usuario
        if form.is_valid():
            form.save()
            
            username = form.cleaned_data.get('username')
            messages.success(request,f'A sua conta foi criada, agora podes fazer o login.')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    
    return render(request,'users/register.html',{'form':form})

@login_required
def perfil(request):
    if request.method=='POST':
        form_user = UserUpdateForm(request.POST, instance=request.user)
        form_perfil = PerfilUpdateForm(request.POST, request.FILES , instance=request.user.perfil)

        #Verificar se os formulários são válidos 
        if form_user.is_valid() and form_perfil.is_valid():
            form_user.save()
            form_perfil.save()
            messages.success(request,f'Perfil actualizado com sucesso.')
            return redirect('users:perfil')
    else:
        form_user = UserUpdateForm(instance=request.user)
        form_perfil = PerfilUpdateForm(instance=request.user.perfil)
        
    context = {
        'form_user': form_user,
        'form_perfil': form_perfil,
        'title': 'Perfil',
    }
    return render(request,'users/perfil.html',context)

blog_project/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog_project/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/mystyle.css' %}">
    
    {% if title %}
        <title>Blog - {{title}}</title>
    {% else %}
        <title>Blog</title>
    {% endif %}
</head>
<body>
    <!-- Cabeçalho -->
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Light Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active"><a class="nav-link" href="{% url 'blog:home' %}">Blog</a></li>
              </ul>
    
              <div class="navbar-nav mr-2">
                <!-- <a class="nav-link" href="{% url 'users:register' %}">Registar</a> -->
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                  <a class="nav-link" href="/admin">Admin</a>
                {% endif %}
                
                  <a class="nav-link" href="{% url 'blog:post-create' %}">Add Post</a>
                  <a class="nav-link" href="{% url 'users:perfil' %}">Perfil</a>
                  <a class="nav-link" href="{% url 'users:logout' %}">Sair</a>
                {% else %}
                  <a class="nav-link" href="{% url 'users:login' %}">Entrar</a>
                {% endif %}
              </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">      
      <br> <br> <br>
      {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </main>

    <script src="{% static 'blog/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog_project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="clearfix div-container">
    
<aside class="aside-left mr-2">
<div class="row">
    {% if posts %}
        {% for post in posts %}   
        <div class="col-md-10 mb-2">
        <div class="card">
            <div class="card-header">
                <img class="rounded-circle img-perfil" style="width: 50px; height: 50px;" src="{{ post.author.perfil.imagem.url }}" alt="">
                <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2 no-decoration">{{ post.author }}</a>
                <small class="text-muted"><cite title="Source Title">{{ post.date_posted|date:"F d, Y H:i" }}</cite></small>
            </div>            
            <div class="card-body mb-0 pt-2">
                <a class="no-decoration text-dark" href="{% url 'blog:post-detail' post.id %}"><h5 class="">{{post.title}}</h5></a>
                <p class="mb-0">{{ post.content }}</p>
            </div>
          </div>
        </div>    
        {% endfor %}
    {% endif %}

    <!-- Paginação -->
    <div class="col-md-10 mb-4">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">First</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}        
 
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num <  page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}        
        
    {% endif %}
    </div>

</div>
</aside>

<aside>
    <div class="card text-white text-dark bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Light Music</div>
        <div class="card-body">
        <h5 class="card-title">Info card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
</aside>
</div>
{% endblock content %}

blog_project/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div style="display: flex; justify-content: center;">
        <div class="border-caixa">
            <!-- formulario de Postagem -->
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Eliminar Post</legend>
                    <h5>Tens a certeza que queres eliminar o post "{{ object.title }}"? </h5>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Sim, Elimine</button>
                    <a href="{% url 'blog:post-detail' object.id %}" class="btn btn-outline-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

blog_project/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="clearfix div-container">
    
<aside class="aside-left mr-2">
<div class="row">
    {% if post %}
        <div class="col-md-10 mb-2">
        <div class="card">
            <div class="card-header">
                <img class="rounded-circle img-perfil" style="width: 50px; height: 50px;" src="{{ post.author.perfil.imagem.url }}" alt="">
                <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2 no-decoration">{{ post.author }}</a>
                <small class="text-muted"><cite title="Source Title">{{ post.date_posted|date:"F d, Y H:i" }}</cite></small>
            </div>            
            <div class="card-body mb-0 pt-2">
                <h5 class="">{{post.title}}</h5>
                <p class="mb-0">{{ post.content }}</p>
                
                <!-- verificar se o post foi criado pelo usuario logado -->
                {% if post.author == user %}
                <div class="mt-2 border-top pt-2" style="margin-bottom: -6px;">
                    <a href="{% url 'blog:post-update' post.id %}" class="btn btn-outline-info">Editar</a>
                    <a href="{% url 'blog:post-delete' post.id %}" class="btn btn-outline-danger">Eliminar</a>
                </div>
                {% endif %}
            </div>
          </div>
        </div>    
    {% endif %}
</div>
</aside>

<aside>
    <div class="card text-white text-dark bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Light Music</div>
        <div class="card-body">
        <h5 class="card-title">Info card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
</aside>
</div>
{% endblock content %}

blog_project/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div style="display: flex; justify-content: center;">
        <div class="border-caixa">
            <!-- formulario de Postagem -->
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Blog Post</legend>
                    {{ form|crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Postar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

blog_project/blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="clearfix div-container">
    
<aside class="aside-left mr-2">
<div class="row mb-5">
    {% if posts %}
        <h4 class="ml-3">Posts de {{ view.kwargs.username }}  ({{ page_obj.paginator.count }}) </h4>
        {% for post in posts %}   
        <div class="col-md-10 mb-2">
        <div class="card">
            <div class="card-header">
                <img class="rounded-circle img-perfil" style="width: 50px; height: 50px;" src="{{ post.author.perfil.imagem.url }}" alt="">
                <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2 no-decoration">{{ post.author }}</a>
                <small class="text-muted"><cite title="Source Title">{{ post.date_posted|date:"F d, Y H:i" }}</cite></small>
            </div>            
            <div class="card-body mb-0 pt-2">
                <a class="no-decoration text-dark" href="{% url 'blog:post-detail' post.id %}"><h5 class="">{{post.title}}</h5></a>
                <p class="mb-0">{{ post.content }}</p>
            </div>
          </div>
        </div>    
        {% endfor %}
    {% endif %}

    <!-- Paginação -->
    <div class="col-md-10">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">First</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}        
 
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num <  page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}        
        
    {% endif %}
    </div>

</div>
</aside>

<aside>
    <div class="card text-white text-dark bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Light Music</div>
        <div class="card-body">
        <h5 class="card-title">Info card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
</aside>
</div>
{% endblock content %}

blog_project/users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div style="display: flex; justify-content: center;">
        <div class="border-caixa" style="width: 300px;">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Entrar</legend>
                    {{ form|crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Entrar</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Não possui uma conta?<a class="ml-1 no-decoration" href="{% url 'users:register' %}">Criar conta</a>
                </small>
            </div>
        </div>
    </div>
    <br> <br>
{% endblock content %}

blog_project/users/templates/users/logout.html
{% extends 'blog/base.html' %}
{% block content %}
    <br><br>
    <h2>Sessão terminada com sucesso</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="no-decoration" href="{% url 'users:login' %}">Entrar novamente</a>
                <br>
                <a class="no-decoration" href="{% url 'blog:home' %}">Ir a página inicial</a>
                <br>
                <a class="no-decoration" href="{% url 'users:register' %}">Registar-se</a>
            </small>
        </div>
    <br> <br>
{% endblock content %}

blog_project/users/templates/users/perfil.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-6 border-caixa" style="border-radius: 5px;">
            <div class="media mb-2">
                <img class="rounded-circle img-perfil" src="{{ user.perfil.imagem.url }}" alt="">
                <div class="media-body">
                    <h4 class="border-bottom pb-1">{{ user.username }}</h4>
                    <p class="text-secondary mt-0">{{ user.email }}</p>
                </div>
            </div>
            <!-- form -->
            <!-- formulario de actualizar perfil -->
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Perfil</legend>
                    {{ form_user|crispy}}
                    {{ form_perfil|crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Update</button>
                </div>
            </form>
            
        </div>
    </div>
{% endblock content %}

blog_project/users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div style="display: flex; justify-content: center;">
        <div class="border-caixa">
            <!-- formulario de registo -->
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Regista-se Hoje</legend>
                    {{ form|crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Registar</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Já possui uma conta? <a class="ml-1 no-decoration" href="{% url 'users:login' %}">Entrar</a>
                </small>
            </div>
        </div>
    </div>
    <br> <br>
{% endblock content %}